-- +goose Up
CREATE TABLE cms_article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(200),
    lifecycle VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (lifecycle IN ('active', 'archived')),
    slug_locked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cms_article_slug UNIQUE (slug),
    CONSTRAINT ck_cms_article_slug CHECK (slug IS NULL OR length(slug) BETWEEN 1 AND 200)
);
CREATE TABLE cms_working_draft (
    article_id BIGINT PRIMARY KEY REFERENCES cms_article(id) ON DELETE RESTRICT,
    version BIGINT NOT NULL CHECK (version >= 1),
    title TEXT NOT NULL DEFAULT '',
    markdown TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    display_date TIMESTAMP WITH TIME ZONE,
    saved_at TIMESTAMP WITH TIME ZONE NOT NULL,
    saved_by BIGINT NOT NULL REFERENCES sys_user(id)
);
CREATE TABLE cms_article_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL REFERENCES cms_article(id) ON DELETE RESTRICT,
    version BIGINT NOT NULL CHECK (version >= 1),
    slug VARCHAR(200) NOT NULL DEFAULT '',
    title TEXT NOT NULL,
    markdown TEXT NOT NULL,
    summary TEXT NOT NULL,
    display_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES sys_user(id),
    CONSTRAINT uk_cms_article_revision_version UNIQUE(article_id, version)
);
CREATE INDEX idx_cms_article_revision_article ON cms_article_revision(article_id, id);
CREATE INDEX idx_cms_working_draft_saved ON cms_working_draft(saved_at, article_id);
-- +goose StatementBegin
CREATE FUNCTION cms_reject_revision_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'article revisions are immutable';
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd
CREATE TRIGGER cms_article_revision_immutable BEFORE UPDATE OR DELETE ON cms_article_revision
FOR EACH ROW EXECUTE FUNCTION cms_reject_revision_mutation();

-- +goose Down
DROP TABLE IF EXISTS cms_article_revision;
DROP FUNCTION IF EXISTS cms_reject_revision_mutation();
DROP TABLE IF EXISTS cms_working_draft;
DROP TABLE IF EXISTS cms_article;
