-- +goose Up
CREATE TABLE cms_site_config (id BIGINT PRIMARY KEY CHECK(id=1),version BIGINT NOT NULL CHECK(version>=1),data TEXT NOT NULL,saved_at TIMESTAMP WITH TIME ZONE NOT NULL,saved_by BIGINT NOT NULL REFERENCES sys_user(id));
CREATE TABLE cms_config_revision (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,version BIGINT NOT NULL UNIQUE,data TEXT NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL,created_by BIGINT NOT NULL REFERENCES sys_user(id));
-- +goose StatementBegin
CREATE FUNCTION cms_reject_config_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'config revisions are immutable'; END; $$ LANGUAGE plpgsql;
-- +goose StatementEnd
CREATE TRIGGER cms_config_revision_immutable BEFORE UPDATE OR DELETE ON cms_config_revision FOR EACH ROW EXECUTE FUNCTION cms_reject_config_mutation();
-- +goose Down
DROP TABLE cms_config_revision;
DROP FUNCTION cms_reject_config_mutation();
DROP TABLE cms_site_config;
