-- +goose Up
CREATE TABLE cms_git_push(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, release_id BIGINT NOT NULL REFERENCES cms_release(id),
 release_key TEXT NOT NULL, manifest TEXT NOT NULL, manifest_hash TEXT NOT NULL, repository TEXT NOT NULL, branch TEXT NOT NULL,
 source_repository TEXT NOT NULL, source_sha TEXT NOT NULL, input_hash TEXT NOT NULL DEFAULT '', prepared BOOLEAN NOT NULL DEFAULT FALSE,
 status TEXT NOT NULL CHECK(status IN('queued','running','succeeded','failed','interrupted','superseded')), error TEXT NOT NULL DEFAULT '',
 planned_sha TEXT NOT NULL DEFAULT '', commit_sha TEXT NOT NULL DEFAULT '', unchanged BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, created_by BIGINT NOT NULL REFERENCES sys_user(id)
);
CREATE INDEX idx_git_push_queue ON cms_git_push(status,id);
CREATE INDEX idx_git_push_target ON cms_git_push(repository,branch,id);
CREATE TABLE cms_git_push_attempt(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id BIGINT NOT NULL REFERENCES cms_git_push(id), status TEXT NOT NULL,
 planned_sha TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '', created_at TIMESTAMP WITH TIME ZONE NOT NULL, finished_at TIMESTAMP WITH TIME ZONE
);
CREATE TABLE cms_git_push_request(key TEXT PRIMARY KEY,actor_id BIGINT NOT NULL REFERENCES sys_user(id),task_id BIGINT NOT NULL REFERENCES cms_git_push(id),operation TEXT NOT NULL);
-- +goose Down
DROP TABLE cms_git_push_request;
DROP TABLE cms_git_push_attempt;
DROP TABLE cms_git_push;
