import { useEffect, useRef, useState } from "react";
import { getPublication, getPreviewAccess, retryPublication, publicationKind, publicationStatus, getWorkerStatus, workerState, type WorkerStatus, type PublishTask } from "@/api/publishing";
import { buildApiUrl } from "@/lib/http";
import { getErrorMessage } from "@/lib/api-error";
import { PermissionGuard } from "@/components/auth/permission-guard";
import { ContentCard } from "@/components/common/content-card";
import { Button } from "@/components/ui/button";
export function PublicationTask({ id, onSuccess, publicUrl }: { id: number; onSuccess?: () => void; publicUrl?:string }) {
 const [worker, setWorker] = useState<WorkerStatus | null>(null);
 const [task, setTask] = useState<PublishTask | null>(null); const [error, setError] = useState(""); const [url, setUrl] = useState(""); const [busy, setBusy] = useState(false); const [generation, setGeneration] = useState(0); const retryKey = useRef<string | null>(null); const callback = useRef(onSuccess); callback.current = onSuccess;
 useEffect(() => { const controller = new AbortController(); let timer: number | undefined;
 const refresh = async () => { try { const value = await getPublication(id, controller.signal); if (controller.signal.aborted) return; setTask(value);setError(""); if (value.status === "queued") { try { const state = await getWorkerStatus(); if (!controller.signal.aborted) setWorker(state); } catch { /* Task access may be broader than executor visibility. */ } } if (value.status === "queued" || value.status === "running") timer = window.setTimeout(() => void refresh(), 1500); else if (value.status === "succeeded") callback.current?.(); } catch (err) { if (!controller.signal.aborted) setError(getErrorMessage(err, "读取任务失败")); } }; void refresh(); return () => { controller.abort(); window.clearTimeout(timer); }; }, [id, generation]);
 async function retry() { setBusy(true); retryKey.current ??= crypto.randomUUID(); try { setTask(await retryPublication(id, retryKey.current)); retryKey.current = null; setGeneration((n) => n + 1); } catch (err) { setError(getErrorMessage(err, "重试提交失败，可继续使用相同请求重试")); } finally { setBusy(false); } }
 async function preview() { try { const access = await getPreviewAccess(id); setUrl(buildApiUrl(access.url)); } catch (err) { setError(getErrorMessage(err, "预览认证失败")); } }
 return <ContentCard title="发布结果" description={task ? `${publicationKind[task.kind]} · ${publicationStatus[task.status] ?? task.status}` : "加载中…"}>{task && <div className="space-y-space-3">{task.status === "queued" && worker && <p role="status">{workerState[worker.state] ?? worker.state}{worker.error ? ` · ${worker.error}` : ""}</p>}{task.status === "succeeded" && <p role="status">{task.kind === "preview" ? "网站效果预览已生成" : task.kind === "unpublish" ? "文章已下线" : "已上线"}</p>}{task.status === "succeeded" && task.kind !== "preview" && task.kind !== "unpublish" && publicUrl && <a href={publicUrl} target="_blank" rel="noreferrer" className="text-primary">查看网站 / 文章</a>}
 {task.articleId && <a href={`/content/articles/${task.articleId}`} className="text-primary">返回文章，发布最新修改</a>}{task.error && <p role="alert" className="text-error">{task.error}</p>}<div className="flex gap-space-3"><Button onClick={() => setGeneration((n) => n + 1)}>刷新</Button>{["failed", "interrupted"].includes(task.status) && <PermissionGuard permissionCode={task.kind === "config" ? "content:config:publish" : task.kind === "preview" ? "content:article:edit" : "content:publish"}><Button disabled={busy} onClick={() => void retry()}>重试原版本</Button></PermissionGuard>}{task.kind === "preview" && task.status === "succeeded" && <Button onClick={() => void preview()}>查看网站效果预览</Button>}</div><details><summary className="cursor-pointer text-sm text-text-secondary">技术诊断 · 任务 #{id}</summary><p>目标修订 {task.revisionId ?? task.configRevisionId ?? "私有快照"}</p>{task.attempts?.map((attempt) => <div key={attempt.id} className="border-t border-border pt-space-3"><p>尝试 #{attempt.id} · {publicationStatus[attempt.status]} · 基线 {attempt.baselineReleaseId ?? "空站点"}</p><p className="break-all text-sm text-text-secondary">产物 {attempt.releaseKey} · {attempt.error}</p></div>)}</details></div>}{error && <p role="alert" className="text-error">{error}</p>}{url && <iframe title="真实 Astro 私有预览" src={url} className="mt-space-4 h-[720px] w-full rounded-control border border-border" sandbox="allow-same-origin" />}</ContentCard>;
}
